name: macOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install meson ninja libass wxmac icu4c ffms2 boost glib

      - name: Build Aegisub
        run: |
          export LDFLAGS="-L/usr/local/opt/icu4c/lib"
          export CPPFLAGS="-I/usr/local/opt/icu4c/include"
          export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
          meson builddir -Ddefault_library=static
          ninja -C builddir
