name: macOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install meson ninja libass wxmac icu4c ffms2 boost glib

      - name: Build Aegisub
        run: |
          MSYSTEM= meson builddir -Ddefault_library=static
          ninja -C builddir
