name: Windows Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            gettext
            curl
            unzip
            tree
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-wxWidgets
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-libass
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-ffms2
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-imagemagick

      - name: Build Aegisub
        run: |
          meson builddir -Dbuildtype=release -Ddefault_library=static
          ninja -C builddir

      - name: Create installer
        run: |
          DESTDIR=$PWD/builddir/installdir meson install --no-rebuild -C builddir
          cd packages/win_installer
          curl -o "innosetup.zip" https://hikari.butaishoujo.moe/b/acc8d97c/innosetup.zip
          unzip innosetup.zip
          curl -o "aegisub-codecs.zip" https://mugen.karaokes.moe/downloads/aegisub-codecs.zip
          unzip aegisub-codecs.zip
          mkdir Amaranth
          cd Amaranth
          curl -o "Amaranth.zip" https://hikari.butaishoujo.moe/b/a416196e/Amaranth.zip
          unzip Amaranth.zip
          cd ..
          ln -s ../../builddir/installdir/a/_temp/msys/msys64/mingw64 install
          ldd install/bin/aegisub
          mkdir po
          for i in install/share/locale/*; do
              cp -v $i/LC_MESSAGES/aegisub.mo po/$(basename $i).mo
          done
          for i in /mingw64/share/locale/*; do
              [ -e $i/LC_MESSAGES/wxstd.mo ] && cp -v $i/LC_MESSAGES/wxstd.mo po/wxstd-$(basename $i).mo
          done
          mkdir libs
          for l in $(ldd install/bin/aegisub | grep -o '=>.*' | cut -d' '  -f2); do
              echo $l
              cp $l libs/
          done
          tree
          innosetup/ISCC.exe aegisub3.iss

      - uses: actions/upload-artifact@v2
        with:
          name: Aegisub-Japan7-x64.exe
          path: packages\win_installer\output\Aegisub-Japan7-x64.exe
