name: Windows Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            openssl
            ninja
            nasm
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-wxWidgets
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ffms2
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-python-pip
      - name: CI-Build
        run: |
          MSYSTEM= pip install meson
          MSYSTEM= meson builddir -Ddefault_library=static
          ninja -C builddir

