name: Windows Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            gettext
            curl
            unzip
            tree
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-cmake

      - name: Build Aegisub
        run: |
          MSYSTEM= meson builddir -Dbuildtype=release -Ddefault_library=static
          ninja -C builddir

      - name: Create installer
        run: |
          tree
          curl -o "aegisub-codecs.zip" https://mugen.karaokes.moe/downloads/aegisub-codecs.zip
          for i in po/*.po; do
            msgfmt -o $(basename $i .po).mo $i
          done
          cd packages/win_installer
          curl -o "innosetup.zip" https://hikari.butaishoujo.moe/b/52a01bb4/innosetup.zip
          unzip innosetup.zip
          innosetup/ISCC.exe aegisub3.iss
